import globals from 'globals';

export default [
  {
    files: ['scripts/static/jarvis_main.js', 'scripts/static/jarvis_mixing.js', 'scripts/static/recorder.js', 'scripts/static/voice_print.js', 'scripts/static/js/terminal_code.js', 'scripts/static/js/voice_lab.js', 'scripts/static/js/stt.js', 'scripts/static/js/tasks_tab.js', 'scripts/static/js/welcome.js', 'scripts/static/js/eq_parametric.js', 'scripts/static/js/audio_mire.js', 'scripts/static/js/eq_music.js', 'scripts/static/js/audio_viz.js', 'scripts/static/js/gpu_monitor.js', 'scripts/static/js/settings_llm.js', 'scripts/static/js/dsp_audio.js', 'scripts/static/js/audio_rack.js', 'scripts/static/js/chat_ui.js', 'scripts/static/js/chat_core.js', 'scripts/static/js/boot_init.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...globals.es2022,
        // Bibliothèques externes chargées via <script>
        hljs: 'readonly',
        Terminal: 'readonly',
        FitAddon: 'readonly',
        monaco: 'readonly',
        // Symboles partagés cross-file entre jarvis_main.js et jarvis_mixing.js
        // (audio nodes, helpers, fonctions globales)
        _cssVar: 'writable',
        _esc: 'writable',
        _ctx: 'writable',
        audioCtx: 'writable',
        analyserL: 'writable',
        analyserR: 'writable',
        _datAnL: 'writable',
        _datAnR: 'writable',
        _dspGainNode: 'writable',
        _dspCompressor: 'writable',
        _dspLimiter: 'writable',
        _dspEqLow: 'writable',
        _dspEqMid: 'writable',
        _dspEqHigh: 'writable',
        _dspEqAir: 'writable',
        _jarvisPreGain: 'writable',
        _jarvisBypassGain: 'writable',
        _mixVuState: 'writable',
        datPLAY: 'writable',
        datPAUSE: 'writable',
        datSTOP: 'writable',
        mixRefreshDevices: 'writable',
        queueSpeech: 'writable',
        // Symboles cross-file vers recorder.js et voice_print.js
        _SAMPLE_RATE: 'readonly',
        _disp: 'writable',
        setEqBand: 'writable',
        drawEqCurve: 'writable',
        _dspSchedulePush: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/terminal_code.js
        // (Terminal CODE extrait — chantier 2026-05-14 · scope global partagé)
        _SOC_REFRESH_MS: 'readonly',
        _devWs: 'writable',
        _devXterm: 'writable',
        _devFit: 'writable',
        _devHostKey: 'writable',
        _devSetStatus: 'writable',
        sendMessage: 'writable',
        setModeSoc: 'writable',
        devTerminalOpen: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/stt.js
        // (STT WHISPER extrait — chantier 2026-05-14)
        stopJarvis: 'writable',
        sttToggle: 'writable',
        sttCheckStatus: 'writable',
        _currentAudioSource: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/voice_lab.js
        // (VOICE LAB IIFE extrait — chantier 2026-05-14)
        escHtml: 'writable',
        setDspLocalVoice: 'writable',
        setTtsEngine: 'writable',
        stopAudio: 'writable',
        analyser: 'writable',
        playSentence: 'writable',
        switchVoice: 'writable',
        setDspSpeed: 'writable',
        setDspPitch: 'writable',
        setDspVolume: 'writable',
        updateSliderPct: 'writable',
        _connectStereoSource: 'writable',
        _dspPitchSemi: 'writable',
        _dspPlaybackRate: 'writable',
        _fetchDspParams: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/tasks_tab.js + js/welcome.js
        // (TÂCHES TAB + WELCOME extraits — chantier dette 2026-05-14)
        _TASKS_POLL_MS: 'readonly',
        _DSP_PUSH_MS: 'readonly',
        _EQ_REDRAW_MS: 'readonly',
        _buildChatPayload: 'writable',
        _startPreloader: 'writable',
        loadWelcome: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/eq_parametric.js
        // (EQ PARAMÉTRIQUE extrait — chantier dette 2026-05-14)
        EQ_BANDS: 'readonly',
        SPEC_PRESETS: 'readonly',
        _dspAnalyser: 'writable',
        _dspDataArray: 'writable',
        _dspVoiceBypass: 'writable',
        _dspVoiceDecoupled: 'writable',
        _eqDrag: 'writable',
        _eqFreqRange: 'writable',
        _eqGhost: 'writable',
        _eqGhostAlpha: 'writable',
        _eqHoverX: 'writable',
        _eqLastCombined: 'writable',
        _eqMemLoad: 'writable',
        _eqState: 'writable',
        _eqVoiceCoupled: 'writable',
        _rackSpecMode: 'writable',
        _specMode: 'writable',
        _specPeaks: 'writable',
        _updateEqCoupleBadges: 'writable',
        _wfCanvas: 'writable',
        _wfColor: 'writable',
        _wfCtx2: 'writable',
        eqBqCoeffs: 'writable',
        eqBqResponse: 'writable',
        eqPushNow: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/eq_music.js + js/audio_mire.js
        // (EQ MUSIC + MIRE extraits — chantier dette 2026-05-14)
        DAT_EQ_BANDS: 'readonly',
        _TTS_STATUS_POLL_MS: 'readonly',
        _canvasCoords: 'writable',
        _datEqBandIdx: 'writable',
        _dspInited: 'writable',
        _dspRafId: 'writable',
        _dspVolume: 'writable',
        _eqPanelOn: 'writable',
        _lastLocalEngine: 'writable',
        _syncDefaultEngineButtons: 'writable',
        _syncRangeSlider: 'writable',
        addMessage: 'writable',
        datEqSetFreq: 'writable',
        datEqSetQ: 'writable',
        datEqSetType: 'writable',
        datEqToggleBypass: 'writable',
        drawDatEqCurve: 'writable',
        eqSetFreq: 'writable',
        eqSetQ: 'writable',
        initDsp: 'writable',
        pushDspParamsToBackend: 'writable',
        setDatEqBand: 'writable',
        setDspCompressor: 'writable',
        setDspGain: 'writable',
        setKokoroSpeed: 'writable',
        startDspDraw: 'writable',
        switchTab: 'writable',
        syncDspVoices: 'writable',
        testDspVoice: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/audio_viz.js
        // (AUDIO VIZ extrait — chantier dette 2026-05-14)
        _analyserEnabled: 'writable',
        _drawGrMeter: 'writable',
        _ensureAudioCtx: 'writable',
        _haasDelayNode: 'writable',
        _haasGainNode: 'writable',
        _lastJarvisText: 'writable',
        _scopeGain: 'writable',
        _setAllReplayBusy: 'writable',
        _specBinMap: 'writable',
        _specColorTable: 'writable',
        _stereoActive: 'writable',
        busy: 'writable',
        ttsEnabled: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/settings_llm.js
        // (SETTINGS LLM extrait — chantier dette 2026-05-14)
        _LS_PROMPT_PROFILE: 'readonly',
        _clearAfter: 'writable',
        _fetchFacts: 'writable',
        _fetchLlmParams: 'writable',
        _fetchPromptProfiles: 'writable',
        _jwarn: 'writable',
        _stColor: 'writable',
        _updateActivePromptBadge: 'writable',
        loadPromptProfiles: 'writable',
        updateImpactBars: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/dsp_audio.js
        // (DSP AUDIO SYSTEM extrait — chantier dette 2026-05-14)
        _FX2: 'writable',
        _fx2Type: 'writable',
        _fx2Vals: 'writable',
        _fxActive: 'writable',
        _fxConvolver: 'writable',
        _fxDryGain: 'writable',
        _fxRefreshIr: 'writable',
        _fxSetWetDry: 'writable',
        _fxType: 'writable',
        _fxWetGain: 'writable',
        _refreshDspSliders: 'writable',
        _stereoWidth: 'writable',
        _updateDspChainStatus: 'writable',
        eqSetType: 'writable',
        eqToggleBypass: 'writable',
        rackInitFaders: 'writable',
        rackSyncHaasDelay: 'writable',
        rackSyncStereoWidth: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/boot_init.js
        // (BOOT SEQUENCE + RACK FX + INIT extraits — chantier dette 2026-05-14)
        _BOOTID_POLL_MS: 'readonly',
        _COVER_SAFE_MS: 'readonly',
        _DRAW_INTERVAL_MS: 'readonly',
        _LS_MODE: 'readonly',
        _MODE_CODE: 'readonly',
        _MODE_CODE_REASONING: 'readonly',
        _MODE_GENERAL: 'readonly',
        _TICK_INTERVAL_MS: 'readonly',
        _VOIX_PULSE_MS: 'readonly',
        _applyModeProfile: 'writable',
        _clearUnitVu: 'writable',
        _compActive: 'writable',
        _dfActive: 'writable',
        _fxUpdateCudaScreen: 'writable',
        _fxVuLevel: 'writable',
        _jarvisMode: 'writable',
        _patchDsp: 'writable',
        _pollOllamaStatus: 'writable',
        _rackUpdateVu: 'writable',
        _rackVuInterval: 'writable',
        _updateModeBtn: 'writable',
        checkWebStatus: 'writable',
        closeCodeModal: 'writable',
        loadMemory: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/audio_rack.js
        // (AI AUDIO RACK + helpers EQ extraits — chantier dette 2026-05-15)
        _rackSyncFromDsp: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/gpu_monitor.js
        // (GPU MONITOR extrait — anneaux CPU/RAM/GPU/VRAM — chantier dette 2026-05-15)
        _POLL_STATS_MS: 'readonly',
        _VRAM_POLL_MS: 'readonly',
        _VRAM_TOTAL: 'writable',
        _statsPollTimer: 'writable',
        drawChart: 'writable',
        graphs: 'writable',
        pollStats: 'writable',
        // Symboles cross-file jarvis_main.js ↔ js/chat_ui.js
        // (CHAT UI extrait — history, addMessage, markdown, Monaco, mémoire LT — chantier dette 2026-05-15)
        _COPY_RESET_MS: 'readonly',
        // Symboles cross-file jarvis_main.js ↔ js/chat_core.js
        // (CHAT CORE extrait — sendMessage, SSE, modes, diagnostic — chantier dette 2026-05-15)
        _CR_POLL_MS: 'readonly',
        _chatAbortController: 'writable',
        _codeStore: 'writable',
        _hideModelPopup: 'writable',
        _refreshVramNow: 'writable',
        _setStopBtn: 'writable',
        _showModelPopup: 'writable',
        _updateHeaderLLM: 'writable',
        addToolEvent: 'writable',
        highlightCode: 'writable',
        renderMarkdown: 'writable',
        saveMemory: 'writable',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none',
      }],
      'no-redeclare': 'off',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-constant-condition': ['warn', { checkLoops: false }],
      'no-unreachable': 'warn',
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-func-assign': 'error',
      'no-self-assign': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'scripts/static/src/**',
      'scripts/static/jarvis_main.bundle.js',
      'scripts/static/jarvis_main.bundle.js.map',
      'scripts/static/highlight.min.js',
      'scripts/static/xterm*.js',
      'tests/**',
      'playwright.config.js',
    ],
  },
];
